### ISSUE TITLE
Missing symbols on aarch64-unknown-linux-musl

### ISSUE THREAD

**Issue by Amanieu** [rust-lang/compiler-builtins#201]
When compiling a simple hello world crate for aarch64-unknown-linux-musl, I get the following error:
```
          /home/amanieu/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/aarch64-unknown-linux-musl/lib/liblibc-3c62182e850a1e7a.rlib(vfprintf.o): In function `fmt_fp':
          vfprintf.c:(.text.fmt_fp+0x178): undefined reference to `__addtf3'
          vfprintf.c:(.text.fmt_fp+0x20c): undefined reference to `__multf3'
          vfprintf.c:(.text.fmt_fp+0x240): undefined reference to `__subtf3'
          vfprintf.c:(.text.fmt_fp+0x250): undefined reference to `__addtf3'
          vfprintf.c:(.text.fmt_fp+0x278): undefined reference to `__addtf3'
          vfprintf.c:(.text.fmt_fp+0x284): undefined reference to `__subtf3'
          vfprintf.c:(.text.fmt_fp+0x33c): undefined reference to `__subtf3'
          vfprintf.c:(.text.fmt_fp+0x344): undefined reference to `__multf3'
          vfprintf.c:(.text.fmt_fp+0x4e8): undefined reference to `__multf3'
          vfprintf.c:(.text.fmt_fp+0x548): undefined reference to `__subtf3'
          vfprintf.c:(.text.fmt_fp+0x550): undefined reference to `__multf3'
          vfprintf.c:(.text.fmt_fp+0x828): undefined reference to `__addtf3'
          /home/amanieu/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/aarch64-unknown-linux-musl/lib/liblibc-3c62182e850a1e7a.rlib(frexpl.o): In function `frexpl':
          frexpl.c:(.text.frexpl+0x38): undefined reference to `__multf3'
          collect2: error: ld returned 1 exit status
```

It would seem that the `__addtf3`, `__subtf3` and `__multf3` symbols are used by musl but are not provided by compiler-builtins.

**Comment by asonix** [comment]
Alright, it seems based [on this link](https://gcc.gnu.org/onlinedocs/gccint/Soft-float-library-routines.html) that `__addtf3`, and the other `tf3` functions are expecting `long double` or a 'triple float'. On aarch64, this occupies 128 bits (as demonstrated by my really basic C program I just compiled on a pine64)

```
asonix@pine64:~$ cat test.c 
#include <stdio.h>

int main() {
	float x = 2.0;
	double y = 2.0;
	long double z = 2.0;

	printf("float: %lu\n", sizeof(x));
	printf("double: %lu\n", sizeof(y));
	printf("long double: %lu\n", sizeof(z));
	return 0;
}
asonix@pine64:~$ gcc test.c -o test.bin
asonix@pine64:~$ ./test.bin 
float: 4
double: 8
long double: 16
asonix@pine64:~$ 
```

Whether this means that long doubles occupy the whole 128 bits, or just part of them I am unsure, but my guess would be to implement these with `f128`s

**Comment by Amanieu** [comment]
Fixed by https://github.com/rust-lang/libc/pull/1034.

**Comment by Amanieu** [comment]
Reopening due to https://github.com/rust-lang/libc/pull/1045

**Comment by bbqsrc** [comment]
This bit me recently, and the workaround [here](https://github.com/rust-lang/rust/issues/46651#issuecomment-402850885) is a temporary but functional fix, though it does leave a dry taste in the mouth.

**Comment by ciofeca** [comment]
Fresh install of Rust 1.30 on x86_64, tried to compile, errors still there. _Sigh!_

**Comment by parched** [comment]
@Amanieu can we fix this by applying your libc patch again and making all symbols in this crate weak symbols?

**Comment by Amanieu** [comment]
I think we can link libgcc as `static-nobundle` which should avoid the link error.
